### ISSUE TITLE
InterSystems Testing Manager use a bad ^UnitTestRoot path

### ISSUE THREAD

**Issue by damia13** [intersystems-community/intersystems-testingmanager#25]
Hello,

I use the  "**InterSystems Testing Manager**" extension on a local iris instance in my vscode editor.
I have a problem when i run unit test with vscode extension : the used path is bad.

In my namespace : ^UnitTestRoot="C:\git-data\care_backend\care_core\src\cls\core\test\services"
VS code run test into : C:\git-data\care_backend\care_core\src\cls\core\test\services\daporrov\
**daporrov** is the username the instance.
So, tests are running into a bad directory and i have one error "bad directory"

I don't know why the username is added at the end of the path.
How to fix that ?

Thank you

**Comment by gjsjohnmurray** [comment]
Based on the [instructions](https://github.com/intersystems-community/intersystems-testingmanager#server-preparations) in the extension's README your ^UnitTestRoot node in namespace XXX should end with `\XXX\UnitTestRoot` (see step 2) and the prefix to this should match the Application Path you chose for the `/_vscode` web app you were told to create (see step 1).

When you are using the client-side paradigm to create and manage your unit test class sources, the extension doesn't load and run them directly from their source folder but first copies them to the `{webAppPath}\XXX\UnitTestRoot\{username}` folder. It does this in order to support remote IRIS servers as well as local ones.

**Comment by damia13** [comment]
Thank you for these informations.
It is work well.

**Comment by damia13** [comment]
Thank you for these informations.
It is work well.
